from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# This is a table to hold the summaries that are generated by the users

class Summary(models.Model) :
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User,on_delete=models.CASCADE) # The user that generated the summary

    def __str__(self) :
        return self.title

    def get_absolute_url(self) :
        return reverse('summary-detail', kwargs={'pk': self.pk})

